slice_name: Parked
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 4__table
  viz_type: big_number_total
  metric: count
  adhoc_filters:
  - expressionType: SIMPLE
    subject: device_time
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_x9cko2qzyw_5kotju6fw4w
  - expressionType: SIMPLE
    subject: moving_status
    operator: IN
    operatorId: IN
    comparator:
    - parked
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_cbxmzp9qchs_jkhsvfmvo1
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":4,"type":"table"},"force":false,"queries":[{"filters":[{"col":"device_time","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"moving_status","op":"IN","val":["parked"]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["count"],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"4__table","viz_type":"big_number_total","metric":"count","adhoc_filters":[{"expressionType":"SIMPLE","subject":"device_time","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_x9cko2qzyw_5kotju6fw4w"},{"expressionType":"SIMPLE","subject":"moving_status","operator":"IN","operatorId":"IN","comparator":["parked"],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_cbxmzp9qchs_jkhsvfmvo1"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: dc9da757-a862-417e-bcf4-74aaf40a53c3
version: 1.0.0
dataset_uuid: 1fd2407a-3416-4b34-8306-d95de18edbbb
